# Generated by Django 2.2.6 on 2019-10-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.RemoveField(
            model_name='department',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='department',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='level',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='tree_id',
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
                ('sub_category_name', models.CharField(max_length=50)),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.MainStore')),
            ],
        ),
    ]
